GET https://slackgpt.vercel.ai.jetdevs.io/prod/gpt

###

GET http://localhost:3000/api/hello


### 

POST http://localhost:3000/api/user/4?b=asdfasdddfasdfadf
Content-Type: application/json

{
    "prompt": "who was governor of illinois 1999? only answer with the name of the player.",
    "temperature": 0.7,
    "max_tokens": 100
}

### 
GET http://localhost:3000/api/slack/



### 

GET https://nextjs-api-routes-m7veurbhu-jetdevs.vercel.app/api/user/as


### 

POST http://localhost:3000/gpt/text-davinci-003?max_tokens=100&temp=0.7
Content-Type: application/json

{
    "prompt": "What's the oldest building in the world. Just tell me the name of the building.",
    "temperature": 0.7,
    "max_tokens": 100
}

### 

POST https://vercel.jetdevs.io/api/gpt/code-davinci-001?max_tokens=1000&temp=0.7
Content-Type: application/json

{
    "prompt": "Write a c++ function that takes in a string and returns the string reversed."
}

