GET https://slackgpt.vercel.ai.jetdevs.io/prod/gpt

###

GET http://localhost:3000/api/gpt


### 

POST http://localhost:3000/api/user/4?b=asdfasdddfasdfadf
Content-Type: application/json

{
    "prompt": "who was governor of illinois 1999? only answer with the name of the player.",
    "temperature": 0.7,
    "max_tokens": 100
}

### 
POST http://localhost:3000/api/event
Content-Type: application/json

{
	"token": "z26uFbvR1xHJEdHE1OQiO6t8",
	"team_id": "T061EG9RZ",
	"api_app_id": "A0FFV41KK",
	"event": {
		"type": "reaction_added",
		"user": "U061F1EUR",
		"item": {
			"type": "message",
			"channel": "C061EG9SL",
			"ts": "1464196127.000002"
		},
		"reaction": "slightly_smiling_face",
		"item_user": "U0M4RL1NY",
		"event_ts": "1465244570.336841"
	},
	"type": "event_callback",
	"authed_users": [
		"U061F7AUR"
	],
	"authorizations": [
        {
            "enterprise_id": "E12345",
            "team_id": "T12345",
            "user_id": "U12345",
            "is_bot": false
        }
    ],
	"event_id": "Ev9UQ52YNA",
	"event_context": "EC12345",
	"event_time": 1234567890"
}






### 

POST https://vercel-slack-jetdevs.vercel.app/api/slack/event
Content-Type: application/json

{
    "token": "Jhj5dZrVaK7ZwHHjRyZWjbDl",
    "challenge": "3eZbrw1aBm2rZgRNFdxV2595E9CY3gmdALWMmHkvFXO7tYXAYM8P",
    "type": "url_verification"
}



### 

POST http://localhost:3000/api/gpt/text-davinci-003?max_tokens=100&temp=0.7
Content-Type: application/json

{
    "prompt": "What's the oldest building in the world. Just tell me the name of the building.",
    "temperature": 0.7,
    "max_tokens": 100
}

### 

POST https://vercel.jetdevs.io/api/gpt/code-davinci-001?max_tokens=1000&temp=0.7
Content-Type: application/json

{
    "prompt": "Write a c++ function that takes in a string and returns the string reversed."
}

###

POST https://hooks.slack.com/services/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
Content-type: application/json

{"text":"Hello, World!"}